fps=1
frame_timing=1
cpu_stats=1
cpu_temp=1
gpu_stats=1
gpu_temp=1
gpu_power=1
ram=1
swap=1
vram=1
battery=1
position=top-left
font_size=20
background_alpha=0.72
background_color=070505
text_color=FFFFFF
cpu_color=FF5A1F
gpu_color=B0000A
vram_color=25D9E8
ram_color=F5E4C3
toggle_hud=Shift_R+F12
