[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\xf/home/lookfrost)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x90\0\0\x1\x17\0\0\x5\xed\0\0\x3.\0\0\x2\x94\0\0\x1\x33\0\0\x5\xe9\0\0\x3(\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x94\0\0\x1\x33\0\0\x5\xe9\0\0\x3()

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(600 346)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/lookfrost/Videos/Lain_pixel_art_live_wallpaper%20%5ByBYoBoznvzo%5D.mp4, file:///home/lookfrost/Videos/2026-07-26%2019-34-41.mp4, file:///home/lookfrost/Videos/Lain_pixel_art_live_wallpaper%20%5ByBYoBoznvzo%5D.mkv, file:///home/lookfrost/Downloads/Lain%20pixel%20art%20live%20wallpaper.mp4, file:///home/lookfrost/Lain%20pixel%20art%20live%20wallpaper%20%5ByBYoBoznvzo%5D.mp4, file:///home/lookfrost/Lain%20pixel%20art%20live%20wallpaper%20%5ByBYoBoznvzo%5D.mkv
times=0, 0, 0, 0, 0, 0
